<?php if ( ! defined( 'FW' ) ) {
	die( 'Forbidden' );
}
$options = array(
	'general_settings' => array(
		'title'   => 'General',
		'type'    => 'tab',
		'options' => array(
			'youtube-api-key'         => array(
				'label' => __( 'Yotube Google API Key', 'blockter' ),
				'desc'  => __( 'Enter your Google API youtube Key. Or get it <a href="https://developers.google.com/youtube/v3/getting-started">here</a>', 'blockter' ),
				'type'  => 'text',
			),
			'api-key'         => array(
				'label' => __( 'TMDB API Key', 'blockter' ),
				'desc'  => __( 'Enter your The Movie Database (TMDb) API Key. Or get it <a href="https://developers.themoviedb.org/3/getting-started/introduction">here</a>', 'blockter' ),
				'type'  => 'text',
			),
			'template-style'  => array(
				'label'   => __( 'Template Style', 'blockter' ),
				'desc'    => __( 'Select style for Movie, TV Show single post.', 'blockter' ),
				'type'    => 'select',
				'value'   => 'style-1',
				'choices' => array(
					'style-1' => __( 'Style 1', 'blockter' ),
					'style-2' => __( 'Style 2', 'blockter' ),
				),
			),
			'language-option' => array(
				'label'   => __( 'Import Language', 'blockter' ),
				'desc'    => __( 'Choose language support for importing.', 'blockter' ),
				'type'    => 'select',
				'value'   => 'en',
				'choices' => array(
					'en' => __( 'English', 'blockter' ),
					'ab' => __( 'Abkhazian', 'blockter' ),
					'aa' => __( 'Afar', 'blockter' ),
					'af' => __( 'Afrikaans', 'blockter' ),
					'ak' => __( 'Akan', 'blockter' ),
					'sq' => __( 'Albanian', 'blockter' ),
					'am' => __( 'Amharic', 'blockter' ),
					'ar' => __( 'Arabic', 'blockter' ),
					'an' => __( 'Aragonese', 'blockter' ),
					'hy' => __( 'Armenian', 'blockter' ),
					'as' => __( 'Assamese', 'blockter' ),
					'av' => __( 'Avaric', 'blockter' ),
					'ae' => __( 'Avestan', 'blockter' ),
					'ay' => __( 'Aymara', 'blockter' ),
					'az' => __( 'Azerbaijani', 'blockter' ),
					'bm' => __( 'Bambara', 'blockter' ),
					'ba' => __( 'Bashkir', 'blockter' ),
					'eu' => __( 'Basque', 'blockter' ),
					'be' => __( 'Belarusian', 'blockter' ),
					'bn' => __( 'Bengali (Bangla)', 'blockter' ),
					'bh' => __( 'Bihari', 'blockter' ),
					'bi' => __( 'Bislama', 'blockter' ),
					'bs' => __( 'Bosnian', 'blockter' ),
					'br' => __( 'Breton', 'blockter' ),
					'bg' => __( 'Bulgarian', 'blockter' ),
					'my' => __( 'Burmese', 'blockter' ),
					'ca' => __( 'Catalan', 'blockter' ),
					'ch' => __( 'Chamorro', 'blockter' ),
					'ce' => __( 'Chechen', 'blockter' ),
					'ny' => __( 'Chichewa, Chewa, Nyanja', 'blockter' ),
					'zh' => __( 'Chinese', 'blockter' ),
					'cv' => __( 'Chuvash', 'blockter' ),
					'kw' => __( 'Cornish', 'blockter' ),
					'co' => __( 'Corsican', 'blockter' ),
					'cr' => __( 'Cree', 'blockter' ),
					'hr' => __( 'Croatian', 'blockter' ),
					'cs' => __( 'Czech', 'blockter' ),
					'da' => __( 'Danish', 'blockter' ),
					'dv' => __( 'Divehi, Dhivehi, Maldivian', 'blockter' ),
					'dz' => __( 'Dzongkha', 'blockter' ),
					'eo' => __( 'Esperanto', 'blockter' ),
					'et' => __( 'Estonian', 'blockter' ),
					'ee' => __( 'Ewe', 'blockter' ),
					'fo' => __( 'Faroese', 'blockter' ),
					'fj' => __( 'Fijian', 'blockter' ),
					'fi' => __( 'Finnish', 'blockter' ),
					'fr' => __( 'French', 'blockter' ),
					'ff' => __( 'Fula, Fulah, Pulaar, Pular', 'blockter' ),
					'gl' => __( 'Galician', 'blockter' ),
					'gd' => __( 'Gaelic (Scottish)', 'blockter' ),
					'gv' => __( 'Gaelic (Manx)', 'blockter' ),
					'ka' => __( 'Georgian', 'blockter' ),
					'de' => __( 'German', 'blockter' ),
					'el' => __( 'Greek', 'blockter' ),
					'kl' => __( 'Greenlandic', 'blockter' ),
					'gn' => __( 'Guarani', 'blockter' ),
					'gu' => __( 'Gujarati', 'blockter' ),
					'ht' => __( 'Haitian Creole', 'blockter' ),
					'ha' => __( 'Hausa', 'blockter' ),
					'he' => __( 'Hebrew', 'blockter' ),
					'hz' => __( 'Herero', 'blockter' ),
					'hi' => __( 'Hindi', 'blockter' ),
					'ho' => __( 'Hiri Motu', 'blockter' ),
					'hu' => __( 'Hungarian', 'blockter' ),
					'is' => __( 'Icelandic', 'blockter' ),
					'io' => __( 'Ido', 'blockter' ),
					'ig' => __( 'Igbo', 'blockter' ),
					'id' => __( 'Indonesian', 'blockter' ),
					'ia' => __( 'Interlingua', 'blockter' ),
					'ie' => __( 'Interlingue', 'blockter' ),
					'iu' => __( 'Inuktitut', 'blockter' ),
					'ik' => __( 'Inupiak', 'blockter' ),
					'ga' => __( 'Irish', 'blockter' ),
					'it' => __( 'Italian', 'blockter' ),
					'ja' => __( 'Japanese', 'blockter' ),
					'jv' => __( 'Javanese', 'blockter' ),
					'kl' => __( 'Kalaallisut, Greenlandic', 'blockter' ),
					'kn' => __( 'Kannada', 'blockter' ),
					'kr' => __( 'Kanuri', 'blockter' ),
					'ks' => __( 'Kashmiri', 'blockter' ),
					'kk' => __( 'Kazakh', 'blockter' ),
					'km' => __( 'Khmer', 'blockter' ),
					'ki' => __( 'Kikuyu', 'blockter' ),
					'rw' => __( 'Kinyarwanda (Rwanda)', 'blockter' ),
					'rn' => __( 'Kirundi', 'blockter' ),
					'ky' => __( 'Kyrgyz', 'blockter' ),
					'kv' => __( 'Komi', 'blockter' ),
					'kg' => __( 'Kongo', 'blockter' ),
					'ko' => __( 'Korean', 'blockter' ),
					'ku' => __( 'Kurdish', 'blockter' ),
					'kj' => __( 'Kwanyama', 'blockter' ),
					'lo' => __( 'Lao', 'blockter' ),
					'la' => __( 'Latin', 'blockter' ),
					'lv' => __( 'Latvian (Lettish)', 'blockter' ),
					'li' => __( 'Limburgish ( Limburger)', 'blockter' ),
					'ln' => __( 'Lingala', 'blockter' ),
					'lt' => __( 'Lithuanian', 'blockter' ),
					'lg' => __( 'Luganda, Ganda', 'blockter' ),
					'lb' => __( 'Luxembourgish', 'blockter' ),
					'gv' => __( 'Manx', 'blockter' ),
					'mk' => __( 'Macedonian', 'blockter' ),
					'mg' => __( 'Malagasy', 'blockter' ),
					'ms' => __( 'Malay', 'blockter' ),
					'ml' => __( 'Malayalam', 'blockter' ),
					'mt' => __( 'Maltese', 'blockter' ),
					'mi' => __( 'Maori', 'blockter' ),
					'mr' => __( 'Marathi', 'blockter' ),
					'mh' => __( 'Marshallese', 'blockter' ),
					'mo' => __( 'Moldavian', 'blockter' ),
					'mn' => __( 'Mongolian', 'blockter' ),
					'na' => __( 'Nauru', 'blockter' ),
					'nv' => __( 'Navajo', 'blockter' ),
					'ng' => __( 'Ndonga', 'blockter' ),
					'nd' => __( 'Northern Ndebele', 'blockter' ),
					'ne' => __( 'Nepali', 'blockter' ),
					'no' => __( 'Norwegian', 'blockter' ),
					'nb' => __( 'Norwegian bokmal', 'blockter' ),
					'nn' => __( 'Norwegian nynorsk	', 'blockter' ),
					'ii' => __( 'Nuosu', 'blockter' ),
					'oc' => __( 'Occitan', 'blockter' ),
					'oj' => __( 'Ojibwe', 'blockter' ),
					'cu' => __( 'Old Church Slavonic, Old Bulgarian', 'blockter' ),
					'or' => __( 'Oriya', 'blockter' ),
					'om' => __( 'Oromo (Afaan Oromo)', 'blockter' ),
					'os' => __( 'Ossetian', 'blockter' ),
					'pi' => __( 'Pali', 'blockter' ),
					'ps' => __( 'Pashto, Pushto', 'blockter' ),
					'fa' => __( 'Persian (Farsi)', 'blockter' ),
					'pl' => __( 'Polish', 'blockter' ),
					'pt' => __( 'Portuguese', 'blockter' ),
					'pa' => __( 'Punjabi (Eastern)', 'blockter' ),
					'qu' => __( 'Quechua', 'blockter' ),
					'rm' => __( 'Romansh', 'blockter' ),
					'ro' => __( 'Romanian', 'blockter' ),
					'ru' => __( 'Russian', 'blockter' ),
					'se' => __( 'Sami', 'blockter' ),
					'sm' => __( 'Samoan', 'blockter' ),
					'sg' => __( 'Sango', 'blockter' ),
					'sa' => __( 'Sanskrit', 'blockter' ),
					'sr' => __( 'Serbian', 'blockter' ),
					'sh' => __( 'Serbo-Croatian', 'blockter' ),
					'st' => __( 'Sesotho', 'blockter' ),
					'tn' => __( 'Setswana', 'blockter' ),
					'ii' => __( 'Sichuan Yi', 'blockter' ),
					'sd' => __( 'Sindhi', 'blockter' ),
					'si' => __( 'Sinhalese', 'blockter' ),
					'ss' => __( 'Siswati', 'blockter' ),
					'sk' => __( 'Slovak', 'blockter' ),
					'sl' => __( 'Slovenian', 'blockter' ),
					'so' => __( 'Somali', 'blockter' ),
					'nr' => __( 'Southern Ndebele', 'blockter' ),
					'es' => __( 'Spanish', 'blockter' ),
					'su' => __( 'Sundanese', 'blockter' ),
					'sw' => __( 'Swahili (Kiswahili)', 'blockter' ),
					'ss' => __( 'Swati', 'blockter' ),
					'sv' => __( 'Swedish', 'blockter' ),
					'tl' => __( 'Tagalog', 'blockter' ),
					'ty' => __( 'Tahitian', 'blockter' ),
					'tg' => __( 'Tajik', 'blockter' ),
					'ta' => __( 'Tamil', 'blockter' ),
					'tt' => __( 'Tatar', 'blockter' ),
					'te' => __( 'Telugu', 'blockter' ),
					'th' => __( 'Thai', 'blockter' ),
					'bo' => __( 'Tibetan', 'blockter' ),
					'ti' => __( 'Tigrinya', 'blockter' ),
					'to' => __( 'Tonga', 'blockter' ),
					'ts' => __( 'Tsonga', 'blockter' ),
					'tr' => __( 'Turkish', 'blockter' ),
					'tk' => __( 'Turkmen', 'blockter' ),
					'tw' => __( 'Twi', 'blockter' ),
					'ug' => __( 'Uyghur', 'blockter' ),
					'uk' => __( 'Ukrainian', 'blockter' ),
					'ur' => __( 'Urdu', 'blockter' ),
					'uz' => __( 'Uzbek', 'blockter' ),
					've' => __( 'Venda', 'blockter' ),
					'vi' => __( 'Vietnamese', 'blockter' ),
					'vo' => __( 'Volapuk', 'blockter' ),
					'wa' => __( 'Wallon', 'blockter' ),
					'cy' => __( 'Welsh', 'blockter' ),
					'wo' => __( 'Wolof', 'blockter' ),
					'fy' => __( 'Western Frisian', 'blockter' ),
					'xh' => __( 'Xhosa', 'blockter' ),
					'yi' => __( 'Yiddish', 'blockter' ),
					'yo' => __( 'Yoruba', 'blockter' ),
					'za' => __( 'Zhuang, Chuang', 'blockter' ),
					'zu' => __( 'Zulu', 'blockter' ),
				),
			),
			'search-options'  => array(
				'type'    => 'checkboxes',
				'label'   => __( 'Search Options', 'blockter' ),
				'desc'    => __( 'Select at least one search option.', 'blockter' ),
				'value'   => array(
					'movie'   => true,
					'tv-show' => true,
					'cast'    => true,
					'news'    => true,
				),
				'choices' => array(
					'movie'   => __( 'Movie', 'blockter' ),
					'tv-show' => __( 'TV Show', 'blockter' ),
					'cast'    => __( 'Cast', 'blockter' ),
					'news'    => __( 'News', 'blockter' ),
				),
				'inline'  => true,
			),
			'vc_overview' => array(
				'type'  => 'switch',
				'value' => 'disable',
				'attr'  => array( 'class' => 'custom-class', 'data-foo' => 'bar' ),
				'label' => __('VC in Movie single', 'blockter'),
				'desc'  => __('This option will support Visual Page builder in Movie single. You need to enable VC for Movie single at first before using this option', 'blockter'),
				'left-choice' => array(
					'value' => 'enable',
					'label' => __('Enable', 'blockter'),
				),
				'right-choice' => array(
					'value' => 'disable',
					'label' => __('Disable', 'blockter'),
				),
			)
		),
	),
	'movie_settings'   => array(
		'title'   => 'Movie',
		'type'    => 'tab',
		'options' => array(
			'import-cast'         => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Cast', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-castmoreinfo' => array(
				'type' =>'switch',
				'value' => 'enable',
				'label' => __( 'Cast more infomation', 'blockter' ),
				'left-choice' => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-genre'        => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Genre', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-collection'   => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Collection', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-poster'       => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Poster', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-banner'       => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Banner', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-trailer'      => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Trailer', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tagline'      => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Tagline', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-overview'     => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Overview', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-director'     => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Director', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-writer'       => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Writer', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-release-date' => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Release Date', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-runtime'      => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Runtime', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-production'   => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Production', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-country'      => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Country', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-language'     => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Language', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
		),
	),
	'tv_settings'      => array(
		'title'   => 'TV Show',
		'type'    => 'tab',
		'options' => array(
			'import-tv-season'       => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Season', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-cast'         => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Cast', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-genre'        => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Genre', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-collection'   => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Collection', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-poster'       => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Poster', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-banner'       => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Banner', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-trailer'      => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Trailer', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-overview'     => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Overview', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-creator'         => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Creator', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-writer'       => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Writer', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-first-air-date'  => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'First Air Date', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-episode-runtime' => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Episode Runtime', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-production'   => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Production', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-country'      => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Country', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
			'import-tv-language'     => array(
				'type'         => 'switch',
				'value'        => 'enable',
				'label'        => __( 'Language', 'blockter' ),
				'left-choice'  => array(
					'value' => 'disable',
					'label' => __( 'Disable', 'blockter' ),
				),
				'right-choice' => array(
					'value' => 'enable',
					'label' => __( 'Enable', 'blockter' ),
				),
			),
		),
	),

);
